# Generated by Django 3.1.3 on 2020-11-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(editable=False, max_length=100)),
                ('method', models.CharField(editable=False, max_length=100)),
                ('scheme', models.CharField(editable=False, max_length=100)),
                ('headers', models.TextField(editable=False)),
                ('body', models.CharField(editable=False, max_length=100)),
                ('user', models.CharField(editable=False, max_length=100)),
                ('info', models.TextField(editable=False, max_length=100)),
                ('COOKIES', models.TextField(editable=False, max_length=100)),
                ('META', models.TextField(editable=False, max_length=100)),
                ('time', models.CharField(editable=False, max_length=100)),
            ],
        ),
    ]
