# Generated by Django 3.1.3 on 2020-11-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='META',
        ),
        migrations.AddField(
            model_name='visitor',
            name='METAdata',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='COOKIES',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='body',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='headers',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='scheme',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
